const incidencias = [
    {
        id:1,
        codigo:"HSARSGC1",
        tipo:"No conformidad",
        estado:"Pendiente",
        resolucion:"Resuelto",
        prioridad:"Urgente",
        responsable:"Carlos Sanchez",
        informador:"Ricardo Short",
        versionAfectada: "Version 1",
        resumen: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        descripcion:"Nisl tincidunt eget nullam non nisi. Tellus rutrum tellus pellentesque eu tincidunt tortor. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Ultricies integer quis auctor elit sed vulputate mi sit. In est ante in nibh mauris cursus.",
        comentario1:"Sin comentarios",
        tomaAccion: "NO",
        accionTomar: "Egestas maecenas pharetra convallis posuere morbi. At urna condimentum mattis pellentesque id nibh tortor id.",
        fechaLimite: "13/4/2021",
        verificacionAccionTomar: "Gravida quis blandit turpis cursus in hac habitasse platea.",
        responsableVerificar: "Ricardo Short",
        comentario2: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        fechaCreacion:"4/6/2020",
        fechaActualizacion:"7/8/2022"
    },
    {
        id:2,
        codigo:"HSARSGC2",
        tipo:"Conformidad",
        estado:"Realizado",
        resolucion:"No Resuelto",
        prioridad:"Media",
        responsable:"Martin Barvece",
        informador:"Lucas Paladino",
        versionAfectada: "Version 2",
        resumen: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        descripcion:"Nisl tincidunt eget nullam non nisi. Tellus rutrum tellus pellentesque eu tincidunt tortor. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Ultricies integer quis auctor elit sed vulputate mi sit. In est ante in nibh mauris cursus.",
        comentario1:"Sin comentarios",
        tomaAccion: "SI",
        accionTomar: "Egestas maecenas pharetra convallis posuere morbi. At urna condimentum mattis pellentesque id nibh tortor id.",
        fechaLimite: "21/6/2021",
        verificacionAccionTomar: "Gravida quis blandit turpis cursus in hac habitasse platea.",
        responsableVerificar: "Lucas Paladino",
        comentario2: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        fechaCreacion:"7/1/2020",
        fechaActualizacion:"5/10/2022"
    },
    {
        id:3,
        codigo:"HSARSGC3",
        tipo:"Accion Preventiva",
        estado:"En proceso",
        resolucion:"Resuelto",
        prioridad:"Baja",
        responsable:"Leandro Mendoza",
        informador:"Marcelo Carabajal",
        versionAfectada: "Version 3",
        resumen: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        descripcion:"Nisl tincidunt eget nullam non nisi. Tellus rutrum tellus pellentesque eu tincidunt tortor. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Ultricies integer quis auctor elit sed vulputate mi sit. In est ante in nibh mauris cursus.",
        comentario1:"Sin comentarios",
        tomaAccion: "SI",
        accionTomar: "Egestas maecenas pharetra convallis posuere morbi. At urna condimentum mattis pellentesque id nibh tortor id.",
        fechaLimite: "27/1/2021",
        verificacionAccionTomar: "Gravida quis blandit turpis cursus in hac habitasse platea.",
        responsableVerificar: "Marcelo Carabajal",
        comentario2: "Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit.",
        fechaCreacion:"3/1/2020",
        fechaActualizacion:"6/9/2022"
    },
]

export default incidencias;